config/routes.rb
Rails.application.routes.draw do
  # devise_for :fans do get 'fans/sign_out' => 'devise/sessions#destroy'
  # end
  devise_for :fans, :controllers => {registrations: 'registrations'}
  root to: 'posts#index'

  #get 'fans/:id/posts' => 'fans#posts', :as => :fans_posts
  get 'posts', to: 'posts#index'

  resources :fans, except: :destroy do
    resources :posts, only: [:new, :create, :show, :edit, :update]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/fan.rb
class Fan < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :posts, dependent: :destroy

end

app/models/fans.rb
class Fan < ActiveRecord::Base
  has_many :posts
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :fan
end

app/models/posts.rb
class Post < ActiveRecord::Base
  belongs_to :posts
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/fans_controller.rb
class FansController < ApplicationController

  #before_action :authenticate_user!, only: [:add_favorite, :remove_favorite]
  # index
  def index
    @fans = Fan.all
  end

  #show
  def show
    @fan = Fan.find(params[:id])
    @posts = @fan.posts.order("id DESC")
  end

  # new
  def new
    @fan = Fan.new
  end

  # create
  def create
    @fan = Fan.create(fan_params)
    redirect_to "/fans/#{@fan.id}"
  end


  # edit
  def edit
    @fan = Fan.find(params[:id])
  end

  # update
  def update
    @fan = Fan.find(params[:id])
    @fan.update(fan_params)

    redirect_to "/fans/#{@fan.id}"
  end

  # destroy
  def destroy
    @fan = Fan.find(params[:id])
    @fan.destroy
    redirect_to "/fans"
  end

  def add_favorite
    @fan = Fan.find(params[:id])
    @fan.favorites.create(user: current_user)
    redirect :back
  end

  def remove_favorite
    Favorite.where(user: current_user).destroy_all
    redirect :back
  end

  private
  def fan_params
    params.require(:fan).permit(:name, :location, :age, :photo)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  # before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]

  # index
  def index
    # @fan = Fan.find(params[:fan_id])
    @posts = Post.order("id DESC")
  end

  # new
  def new
    @fan = Fan.find(params[:fan_id])
    @post = @fan.posts.new

  end

  # create
  def create
    @fan = Fan.find(params[:fan_id])
    @post = @fan.posts.create!(post_params)
    redirect_to fan_post_path(@fan, @post)
  end

  #show
  def show
    @fan = Fan.find(params[:fan_id])
    @post = Post.find(params[:id])
  end

  # edit
  def edit
    @post = Post.find(params[:id])
    @fan = Fan.find(@post.fan_id)
  end

  # update
  def update
    @post = Post.find(params[:id])
    @post.update(post_params)
    @fan = Fan.find(@post.fan_id)
    redirect_to fan_post_path(@fan, @post)
  end

  # # destroy
  # def destroy
  #   @post = Post.find(params[:id])
  #   @post.destroy
  #   @fan = Fan.find(@post.fan_id)
  #
  #   redirect_to fan_path(@fan)
  # end

  private
  def post_params
    params.require(:post).permit(:shoe_name, :shoe_photo, :fan_message, :fan_id)
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private

  def sign_up_params
    params.require(:fan).permit(:name, :location, :age, :photo, :email, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:fan).permit(:name, :location, :age, :photo, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/fans/_form.html.erb
<%= form_for(@fan) do |f| %>
  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: "input-style" %>
  </div>
  <div class="form-group">
    <%= f.label :location %>
    <%= f.text_field :location, class: "input-style"  %>
  </div>
  <div class="form-group">
    <%= f.label :age %>
    <%= f.text_field :age, class: "input-style"  %>
  </div>
  <div class="form-group">
    <%= f.label :photo %>
    <%= f.text_field :photo, class: "input-style"  %>
  </div>
  <%= f.submit class: "form-button-style" %>
<% end %>

app/views/fans/edit.html.erb
<h2>Edit <%= @fan.name %></h2>
<div class="form-style">
  <%= render "form" %>
</div>

app/views/fans/index.html.erb
<h2>Fans</h2>
<%= link_to "Add New Fan", new_fan_path %>
<% @fans.each do |fan| %>
  <%= link_to fan.name, fan_path(fan) %>
<% end %>

app/views/fans/new.html.erb
<h2>New Fans</h2>
<div class="form-style">
  <%= render "form" %>
</div>

app/views/fans/show.html.erb
<div class="profile-photo">
  <img src="<%= @fan.photo %>">
</div>
<div class="fan-info">
  <h2><%= @fan.name %>, <%= @fan.age %></h2>
  <h3><%= @fan.location %></h3>
  <%= link_to 'Home', root_path, class: "nav-button" %>
  <%= link_to 'Edit Profile', edit_fan_path(@fan), class: "nav-button" %>
  <!-- <%= link_to 'Delete Profile', @fan, class: "nav-button", method: :delete %> -->
</div>

<%= link_to new_fan_post_path(@fan) do %>
<div class="new-post-box">
  CREATE NEW POST
</div>
<% end %>

<div class="shoe-wrapper">
    <% @posts.each do |post| %>
      <div class="shoe-container">
          <%= link_to fan_post_path(post.fan_id, post) do %>
            <img src= "<%= post.shoe_photo %>" class="shoe-photo-resize">
          <% end %>
          <p class= "shoe-details">
            <%= post.shoe_name %>
            <%= post.fan_message %>
            <% if (fan_signed_in? && (current_fan.id == post.fan_id)) %>
              <%= link_to "Edit Post", edit_fan_post_path(post.fan_id, post) %>
              <!-- <%= link_to "Delete Post", [@fan, post], method: :delete %> -->
            <% end %>
          </p>
      </div>
      <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tinker's World</title>
    <%= favicon_link_tag "http://assets.macerichepicenter.com/FileManager/_shared/Retailers/Logos/nike-logo-orange-svg_300x300.jpg" %>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <div class="login-info">
      <% if (fan_signed_in? ) %>
          <%= link_to "View Profile", current_fan %>
          <%= link_to "Sign Out", destroy_fan_session_path, :method => :delete %>
      <% else %>
          <%= link_to "Login", new_fan_session_path %>
          <%= link_to "Sign Up", new_fan_registration_path %>
      <% end %>
    </div>
    <%= yield %>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_for [@fan, @post] do |f| %>
  <div class="form-group">
    <%= f.label :shoe_name %>
    <%= f.text_field :shoe_name, class: "input-style" %>
  </div>
  <div class="form-group">
    <%= f.label :shoe_photo %>
    <%= f.text_field :shoe_photo, class: "input-style" %>
  </div>
  <div class="form-group">
    <%= f.label :fan_message %>
    <%= f.text_field :fan_message, class: "input-style" %>
  </div>
  <%= f.submit class: "form-button-style" %>
<% end %>

app/views/posts/edit.html.erb
<h2>Edit <%= @post.shoe_name %> </h2>
<div class="form-style">
  <%= render "form" %>
</div>
<%= link_to "Back", root_path %>

app/views/posts/index.html.erb
<div class="nav-container">
  <!-- header and sub-header -->
  <h2>TINKER'S WORLD</h2>
  <p>Share your favorite Tinker Hatfield shoe designs</p>
</div>

<!-- create the grid for the post -->
<div class="shoe-wrapper">
  <% @posts.each do |post| %>
    <div class= "shoe-container">
      <p class= "shoe-details">
        <%= post.shoe_name %>
        <%= post.fan_message %>
        <% if (fan_signed_in? && (current_fan.id == post.fan_id)) %>
          <%= link_to "Edit Post", edit_fan_post_path(post.fan_id, post) %>
        <% end %>
      </p>
      <%= link_to fan_post_path(post.fan_id, post) do %>
        <img src= "<%= post.shoe_photo %>" class="shoe-photo-resize">
      <% end %>
    </div>
  <% end %>
</div>

<!-- create a footer -->
<footer><a href="http://rodneycurl.com">© 2017 All Rights Reserved Created By Rodney Curl.</a></footer>

app/views/posts/new.html.erb
<h2>New Posts</h2>

<div class="form-style">
  <%= render "form" %>
</div>

app/views/posts/show.html.erb
<%= link_to 'Back', root_path, class: "nav-button" %>
<%= link_to 'Edit Post', edit_fan_post_path(@fan), class: "nav-button" %>
<%= link_to 'Create New Post', new_fan_post_path(@fan), class: "nav-button" %>
<!-- <%= link_to 'Delete Profile', @fan, method: :delete, class: "navbutton" %> -->
<div class="container"
  <div class="img">
    <img src="<%= @post.shoe_photo%>">
    <h2 id="shoe-post-name"><%= @post.shoe_name %></h2>
    <h3><%= @post.fan_message %></h3>
  </div>
</div>